# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Libreoffice and uno dependencies
      run: |
        sudo apt-get install libreoffice python3-uno imagemagick python3.11 python3.11-venv
    - name: Install python environment ${{ matrix.python-version }}
      run: |
        sudo python3.11 -m venv .python3.11 --system-site-packages
        sudo .python3.11/bin/pip install .
        sudo .python3.11/bin/pip install pytest
    - name: Run Tests
      run: |
        sudo .python3.11/bin/pytest -v
