name: Python application

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v6
    - name: Install LibreOffice and uno dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice python3-uno imagemagick gettext
    - name: Install python environment
      run: |
        python -m venv .venv --system-site-packages 
        .venv/bin/pip install . 
        .venv/bin/pip install pytest 
    - name: Run Tests
      run: |
        .venv/bin/pytest -v
    - name: Run Demo Benchmark
      run: |
        .venv/bin/unogenerator_demo --benchmark

