# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "158-create-github-action-testing", "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Libreoffice and uno dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libreoffice libreoffice-script-provider-python python3-uno
        sudo python --version
        sudo python -m uno
        sudo python -c "import uno"
        sudo python -m pip install --upgrade pip
        sudo pip install pytest
        sudo pip install .
        sudo python -c "import uno"
        sudo unogenerator_start
        sudo pytest
